export const rebutanAbi = [
  {
    type: "constructor",
    inputs: [{ name: "sessionBlocks", type: "uint64", internalType: "uint64" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "COOLDOWN_STEP",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ENDURANCE_BPS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "FORTIFY_COST",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "FORTIFY_PROTECT",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "LONG_REIGN_BPS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_SESSION_BLOCKS",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MIN_REIGN",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MIN_SESSION_BLOCKS",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "STAKE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claim",
    inputs: [{ name: "id", type: "uint32", internalType: "uint32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimed",
    inputs: [
      { name: "", type: "uint32", internalType: "uint32" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cooldownRemaining",
    inputs: [{ name: "player", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "current",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct Rebutan.Session",
        components: [
          { name: "startBlock", type: "uint64", internalType: "uint64" },
          { name: "stage2At", type: "uint64", internalType: "uint64" },
          { name: "stage3At", type: "uint64", internalType: "uint64" },
          { name: "endsAt", type: "uint64", internalType: "uint64" },
          { name: "holder", type: "address", internalType: "address" },
          { name: "since", type: "uint64", internalType: "uint64" },
          { name: "reignStart", type: "uint64", internalType: "uint64" },
          { name: "protectedUntil", type: "uint64", internalType: "uint64" },
          { name: "fortified", type: "bool", internalType: "bool" },
          { name: "settled", type: "bool", internalType: "bool" },
          { name: "pot", type: "uint256", internalType: "uint256" },
          { name: "totalWeighted", type: "uint64", internalType: "uint64" },
          { name: "bestReign", type: "uint64", internalType: "uint64" },
          { name: "bestReignHolder", type: "address", internalType: "address" },
          { name: "players", type: "uint32", internalType: "uint32" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "currentStage",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fortify",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "join",
    inputs: [],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "joined",
    inputs: [
      { name: "", type: "uint32", internalType: "uint32" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextStealAllowed",
    inputs: [
      { name: "", type: "uint32", internalType: "uint32" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingWeighted",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protectionRemaining",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "reignRecord",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "session",
    inputs: [{ name: "id", type: "uint32", internalType: "uint32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct Rebutan.Session",
        components: [
          { name: "startBlock", type: "uint64", internalType: "uint64" },
          { name: "stage2At", type: "uint64", internalType: "uint64" },
          { name: "stage3At", type: "uint64", internalType: "uint64" },
          { name: "endsAt", type: "uint64", internalType: "uint64" },
          { name: "holder", type: "address", internalType: "address" },
          { name: "since", type: "uint64", internalType: "uint64" },
          { name: "reignStart", type: "uint64", internalType: "uint64" },
          { name: "protectedUntil", type: "uint64", internalType: "uint64" },
          { name: "fortified", type: "bool", internalType: "bool" },
          { name: "settled", type: "bool", internalType: "bool" },
          { name: "pot", type: "uint256", internalType: "uint256" },
          { name: "totalWeighted", type: "uint64", internalType: "uint64" },
          { name: "bestReign", type: "uint64", internalType: "uint64" },
          { name: "bestReignHolder", type: "address", internalType: "address" },
          { name: "players", type: "uint32", internalType: "uint32" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sessionId",
    inputs: [],
    outputs: [{ name: "", type: "uint32", internalType: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "settle",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "startSession",
    inputs: [{ name: "sessionBlocks", type: "uint64", internalType: "uint64" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "steal",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "stealCount",
    inputs: [
      { name: "", type: "uint32", internalType: "uint32" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint32", internalType: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "weightedHeld",
    inputs: [
      { name: "", type: "uint32", internalType: "uint32" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Claimed",
    inputs: [
      {
        name: "session",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "player",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Fortified",
    inputs: [
      {
        name: "session",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "holder",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "protectedUntil",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Joined",
    inputs: [
      {
        name: "session",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "player",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "pot", type: "uint256", indexed: false, internalType: "uint256" },
      {
        name: "players",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SessionStarted",
    inputs: [
      {
        name: "session",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "startBlock",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
      {
        name: "endsAt",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Settled",
    inputs: [
      {
        name: "session",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "finalHolder",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "totalWeighted",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
      {
        name: "bestReignHolder",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Stolen",
    inputs: [
      {
        name: "session",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "to", type: "address", indexed: true, internalType: "address" },
      {
        name: "atBlock",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
      {
        name: "weightedCredited",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AlreadyClaimed", inputs: [] },
  { type: "error", name: "AlreadyFortified", inputs: [] },
  { type: "error", name: "AlreadyJoined", inputs: [] },
  { type: "error", name: "AlreadyYours", inputs: [] },
  { type: "error", name: "BadSessionLength", inputs: [] },
  { type: "error", name: "CoolingDown", inputs: [] },
  { type: "error", name: "CrownProtected", inputs: [] },
  { type: "error", name: "NotHolder", inputs: [] },
  { type: "error", name: "NotJoined", inputs: [] },
  { type: "error", name: "NotSettled", inputs: [] },
  { type: "error", name: "SessionClosed", inputs: [] },
  { type: "error", name: "SessionLive", inputs: [] },
  { type: "error", name: "SessionRunning", inputs: [] },
  { type: "error", name: "TransferFailed", inputs: [] },
  { type: "error", name: "WrongStake", inputs: [] },
] as const;
